---
- name: Deploy HTML to test servers
  hosts: prod
  become: yes
  remote_user: ansadmin

  tasks:
  - name: Install aptitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest

  - name: Install Docker Module for Python
    pip:
      name: docker
  
  - name: Install git
    apt : name={{item}} state=latest update_cache=yes
    loop:
    - git

  #- name: Ensure docker is at the latest version
    #ansible.builtin.yum:
      #name: docker
      #state: latest

  #- name: Ensure service is enabled
    #command: service docker restart

  - name: Clone the repo
    git: repo=https://github.com/gregk-git/module-3-Git-And-Jenkins-assignment-1 dest=/tmp/gitrepo

  - name: Deploy nginx docker with web files
    docker_container:
      image: nginx:stable
      name: nginx
      state: started
      auto_remove: true
      ports:
        - "80:80"
      volumes:
        - /tmp/gitrepo/:/var/www/html
